- app/navigation/Navigator.scala
- test/controllers/TypeOfParticipantControllerSpec.scala
- test/navigation/NavigatorSpec.scala
> Add routing

- app/assets/stylesheets/partials/_forms.scss
- app/assets/stylesheets/partials/_utilities.scss
- app/controllers/TypeOfParticipantController.scala
- app/controllers/WhatYouNeedController.scala
- app/views/BoughtOrSoldOverThresholdView.scala.html
- app/views/CheckYourAnswersView.scala.html
- app/views/DateTransactionOverThresholdView.scala.html
- app/views/IdentifyLinkedTransactionsView.scala.html
- app/views/PercentageExpectedTurnoverView.scala.html
- app/views/TypeOfParticipantDetailView.scala.html
- app/views/TypeOfParticipantView.scala.html
- app/views/WhatYouNeedView.scala.html
- app/views/components/page_heading.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- migrations/applied_migrations/WhatYouNeed.sh
- test/controllers/WhatYouNeedControllerSpec.scala
- test/views/WhatYouNeedViewSpec.scala
- test/views/behaviours/ViewBehaviours.scala
- test/views/behaviours/YesNoViewBehaviours.scala
Add what you need page and section sub heading top each page.
> Add what you need

- app/controllers/actions/IdentifierAction.scala
- app/models/requests/IdentifierRequest.scala
- generate-my-release-note.sh
- generate-release-notes.sh
- release_notes/AMLS-5274.txt
- test/controllers/actions/AuthActionSpec.scala
- test/views/BoughtOrSoldOverThresholdViewSpec.scala
As above plus added release notes generators.
- none
- manually, unit tests
> Amls 5274 | Auth implementation like in frontend

- app/assets/javascripts/amlsartmarketparticipantfrontend.js
- app/assets/stylesheets/amlsartmarketparticipantfrontend-app.scss
- app/assets/stylesheets/partials/_forms.scss
- app/assets/stylesheets/partials/_typography.scss
- app/views/GovukWrapper.scala.html
- app/views/components/heading.scala.html
- conf/application.conf
- conf/messages.en
- Removed Cookie Notice (by fixing contentSecurityPolicy)
- Added Beta Banner
- Added User Research Banner
- Changed all headings from .heading-large to .heading-xlarge
- Some margin and padding tweaks
**Creating separate tickets for:**
- We moved H1s to inside forms for accessibility. Does this need done? Do we need the scaffolding updating (if not for AMP, then for future services?)
- We place most text in `<p>` tags. Scaffolding places text in .form-hint `<span>`
- Need "Return to about your business" link on question pages
- Need to change "Get help with this page" -> "Is there anything wrong with this page?"
- Need session management / "Sign out" in top left
These are with Geoff, pending a conversation with Martin.
> AMLS-5273 | Bring styling in line with frontend

- app/controllers/CheckYourAnswersController.scala
- app/utils/CheckYourAnswersHelper.scala
- conf/messages.en
- test/utils/CheckYourAnswersHelperSpec.scala
- test/views/BoughtOrSoldOverThresholdViewSpec.scala
- test/views/DateTransactionOverThresholdViewSpec.scala
- test/views/IdentifyLinkedTransactionsViewSpec.scala
- test/views/IndexViewSpec.scala
- test/views/PercentageExpectedTurnoverViewSpec.scala
- test/views/SessionExpiredViewSpec.scala
- test/views/TypeOfParticipantDetailViewSpec.scala
- test/views/TypeOfParticipantViewSpec.scala
- test/views/UnauthorisedViewSpec.scala
- test/views/WhatYouNeedViewSpec.scala
Add new content to AMP journey
Related / Dependant PRs?
N/A
How Has This Been Tested?
Local + Unit
Checklist
[] Breaking change (fix or feature that would cause existing functionality to change).
[/] Build passing.
[/] Unit tests have full coverage.
[]  Unit test approach and implementation has been reviewed with QA (testers). 
[/] Requires acceptance test run.
[/] Appropriate labels added.
[] RELEASE NOTES ADDED.
> Amls 5285 - New content for AMP journey

- app/views/WhatYouNeedView.scala.html
- conf/app.routes
- test/utils/CheckYourAnswersHelperSpec.scala
Change the AMP urls as per the ticket. Alongside changing CYA helper tests. Can someone please confirm that we are keeping the "change" keyword in our edit URLs. If not I shall remove.
> AMLS-5243 | Changed URLs and unit tests

- app/forms/DateTransactionOverThresholdFormProvider.scala
- app/forms/TypeOfParticipantDetailFormProvider.scala
- app/forms/mappings/Constraints.scala
- app/models/TypeOfParticipant.scala
- conf/messages.en
- test/controllers/DateTransactionOverThresholdControllerSpec.scala
- test/forms/DateTransactionOverThresholdFormProviderSpec.scala
- test/forms/TypeOfParticipantDetailFormProviderSpec.scala
Added error handling and updated error messages.
Search for "TODO", these will need to be removed when AMP start date arrives (11th Jan 2020):
- There are checks before performing tests that we are after the AMP start date.
- The start date has temporarily been set to 11th Jan 2019 to facilitate testing
- A "backdoor" has been added to allow users to bypass date checking with 11th April 1905, to facilitate testing.
Manual and unit tests
> AMLS-5244 | Error handling

- conf/application.conf
Adding this localhost changes error message text form to most up to date security policy settings.
> AMLS-5308 | Added contentSecurity localHost for up to date error page

- app/forms/DateTransactionOverThresholdFormProvider.scala
Changed 2019 -> 2020 (backdoor date and if statements in tests still present)
> AMLS-5244 | Restored correct date after testing

- app/views/BoughtOrSoldOverThresholdView.scala.html
- app/views/CheckYourAnswersView.scala.html
- app/views/DateTransactionOverThresholdView.scala.html
- app/views/IdentifyLinkedTransactionsView.scala.html
- app/views/IndexView.scala.html
- app/views/PercentageExpectedTurnoverView.scala.html
- app/views/SessionExpiredView.scala.html
- app/views/TypeOfParticipantDetailView.scala.html
- app/views/TypeOfParticipantView.scala.html
- app/views/UnauthorisedView.scala.html
- app/views/WhatYouNeedView.scala.html
- release_notes/AMLS-5337.txt
- test/views/BoughtOrSoldOverThresholdViewSpec.scala
- test/views/DateTransactionOverThresholdViewSpec.scala
- test/views/IdentifyLinkedTransactionsViewSpec.scala
- test/views/IndexViewSpec.scala
- test/views/PercentageExpectedTurnoverViewSpec.scala
- test/views/SessionExpiredViewSpec.scala
- test/views/TypeOfParticipantDetailViewSpec.scala
- test/views/TypeOfParticipantViewSpec.scala
- test/views/UnauthorisedViewSpec.scala
- test/views/ViewSpecBase.scala
- test/views/WhatYouNeedViewSpec.scala
- test/views/behaviours/StringViewBehaviours.scala
- test/views/behaviours/ViewBehaviours.scala
- test/views/behaviours/YesNoViewBehaviours.scala
Added "- Art market participant - Manage your anti-money laundering supervision - GOV.UK" to the end of page titles and removed space in cases where errors are not displayed.
Manual testing and ran unit tests (unit tests were updated to reflect the new page titles)
> AMLS-5337 | Page titles

- app/config/FrontendAppConfig.scala
- conf/prod.routes
- release_notes/AMLS-5355.txt
- test/utils/CheckYourAnswersHelperSpec.scala
Change the url of AMP FE to be more seamless to the user
https://github.com/hmrc/amls-frontend/pull/1197
https://github.com/hmrc/mdtp-frontend-routes/pull/1145
Local + Unit
> Change the url of AMP FE to be more seamless to the user

- build.sbt
- test/controllers/SessionControllerSpec.scala
- test/forms/mappings/ConstraintsSpec.scala
Excluding automatically generated templates from code coverage report, added missing tests in two files.
- none
- N/A
> Code coverage

- app/utils/CheckYourAnswersHelper.scala
- app/views/BoughtOrSoldOverThresholdView.scala.html
- app/views/PercentageExpectedTurnoverView.scala.html
- conf/messages.en
- test/utils/CheckYourAnswersHelperSpec.scala
- test/views/PercentageExpectedTurnoverViewSpec.scala
> AMLS-5351 | Changed AMP content to match audit

- app/config/FrontendAppConfig.scala
- app/views/GovukWrapper.scala.html
- conf/application.conf
Added GTM to config files and GovUKWrapper
Manually
- [] RELEASE NOTES ADDED.
> AMLS-5361 | Added GTM to amp-frontend

- conf/application.conf
Change GTM container
N/A
To be tested in staging.
> Change GTM container

- app/assets/stylesheets/amlsartmarketparticipantfrontend-app.scss
- app/assets/stylesheets/partials/_focus.scss
- app/assets/stylesheets/partials/_palette.scss
- release_notes/AMLS-5390.txt
Updated palette in AMP front-end.
https://github.com/hmrc/amls-frontend/pull/1219
Manual testing
> AMLS-5390 | Updated palette

- project/AppDependencies.scala
Update play ui version
N/A
Unit + Regression
> Update play ui version

- app/assets/javascripts/amlsartmarketparticipantfrontend.js
- app/assets/stylesheets/amlsartmarketparticipantfrontend-app.scss
- app/views/GovukWrapper.scala.html
- release_notes/AMLS-5477.txt
Removed UR banner from AMP
Manual testing, ran unit tests
> AMLS 5477 | Removed UR Banner from AMP

- app/controllers/actions/IdentifierAction.scala
- release_notes/AMLS-5499.txt
- test/controllers/actions/IdentifierActionSpec.scala
Align auth model with AMLS FE
N/A
Local + Unit
> Align auth model with AMLS FE

- app/controllers/actions/IdentifierAction.scala
Update logging entry in Identifier Action to pass ex as second param
N/A
Unit
> Update logging entry in Identifier Action to pass ex as second param

- app/views/DateTransactionOverThresholdView.scala.html
- app/views/IdentifyLinkedTransactionsView.scala.html
- app/views/PercentageExpectedTurnoverView.scala.html
- app/views/SoldOverThresholdView.scala.html
- app/views/TypeOfParticipantDetailView.scala.html
- app/views/TypeOfParticipantView.scala.html
- app/views/components/answer_section.scala.html
- app/views/components/error_summary.scala.html
- app/views/components/input_checkboxes.scala.html
- app/views/components/input_date.scala.html
- app/views/components/input_radio.scala.html
- app/views/components/input_text.scala.html
- app/views/components/input_yes_no.scala.html
- app/views/components/submit_button.scala.html
- project/AppDependencies.scala
- release_notes/AMLS-5513.txt
- test/views/ViewSpecBase.scala
- test/views/behaviours/CheckboxViewBehaviours.scala
- test/views/behaviours/StringViewBehaviours.scala
- test/views/behaviours/YesNoViewBehaviours.scala
Implement EAB view components into AMP
N/A
Local + Unit + Regression
> Amls 5513 achi

- app/views/components/input_checkboxes.scala.html
- app/views/components/input_date.scala.html
- app/views/components/input_radio.scala.html
- app/views/components/input_yes_no.scala.html
Remove ids from fieldset as causes duplicate ids issue in automated GDS tests
N/A
Local
> Remove ids from fieldset as causes duplicate ids issue in automated GDS tests

- app/config/FrontendAppConfig.scala
- conf/application.conf
- release_notes/AMLS-5588.txt
Correct feedback and get help urls to work in all environments
N/A
Local
> Correct feedback and get help urls to work in all environments

- build.sbt
- release_notes/AMLS-5274.txt
- release_notes/AMLS-5299.txt
- release_notes/AMLS-5325.txt
- release_notes/AMLS-5333.txt
- release_notes/AMLS-5337.txt
- release_notes/AMLS-5355.txt
- release_notes/AMLS-5390.txt
- release_notes/AMLS-5477.txt
- release_notes/AMLS-5499.txt
- release_notes/AMLS-5513.txt
- release_notes/AMLS-5564.txt
- release_notes/AMLS-5588.txt
- release_notes/releases/v1.0.0/v1.0.0-16-12-2019.txt
Generate release notes v1.0.0
N/A
N/A
> Generate release notes v1.0.0

- app/views/components/error_summary.scala.html
- app/views/components/input_checkboxes.scala.html
- app/views/components/input_date.scala.html
- app/views/components/input_radio.scala.html
- app/views/components/input_text.scala.html
- app/views/components/input_textarea.scala.html
- app/views/components/input_yes_no.scala.html
- release_notes/AMLS-5593.txt
Output only one error at a time to reduce visual load for user
N/A
Local
> Output only one error at a time to reduce visual load for user

- release_notes/releases/v1.6.0/v1.6.0-27-01-2020.txt
> Rel notes 1 6 0 new rn

- project/AppDependencies.scala
- project/plugins.sbt
- release_notes/AMLS-5704.txt
- test/connectors/AMLSConnectorSpec.scala
As above.
- none
- regression, unit
> Amls 5704 | Libraries upgrade

- release_notes/AMLS-5704.txt
- release_notes/AMLS-5741.txt
- release_notes/releases/v1.10.0/v1.10.0-04-03-2020.txt
> Fix rel notes error

- app/views/components/input_date.scala.html
- release_notes/AMLS-5844.txt
> Amls 5844 - Removed aria described by whitespace

- app/views/components/input_date.scala.html
- release_notes/AMLS-5096.txt
- test/views/components/inputDateSpec.scala
Change aria described by functionality on date page.
Unit
Manual
> Amls 5906 -  date change aria described by

- release_notes/AMLS-5096.txt
- release_notes/releases/v1.14.0/v1.14.0-22-04-2020.txt
Added release notes for v1.14.0
> Added release notes for v1.14.0

- app/assets/javascripts/amlsartmarketparticipantfrontend.js
- app/views/components/button_link_with_id.scala.html
- release_notes/AMLS-5835.txt
> AMLS-5835 | Updated links that look like buttons to properly mimic the behaviour of a button element

- app/views/components/input_date.scala.html
- release_notes/AMLS-5722.txt
REBASE this branch has been reviewed and tested, this PR is made to make sure commits are signed.
https://github.com/hmrc/amls-art-market-participant-frontend/pull/53
Unit
Manual
> AMLS-5722 | Date input changes for DAC and release notes

- release_notes/AMLS-5722.txt
- release_notes/releases/v1.15.0/v1.15.0-05-05-2020.txt
> Release notes for v1.15.0

- app/utils/CheckYourAnswersHelper.scala
- app/views/CheckYourAnswersView.scala.html
- app/views/IdentifyLinkedTransactionsView.scala.html
- app/views/MainTemplate.scala.html
- app/views/PercentageExpectedTurnoverView.scala.html
- app/views/SoldOverThresholdView.scala.html
- app/views/TypeOfParticipantView.scala.html
- app/views/ViewUtils.scala
- app/views/components/error_summary_with_id.scala.html
- app/views/components/input_checkboxes.scala.html
- app/views/components/repeater_answer_section.scala.html
- conf/messages.en
- release_notes/AMLS-5722.txt
- release_notes/AMLS-5817.txt
- release_notes/AMLS-5835.txt
- test/utils/CheckYourAnswersHelperSpec.scala
- test/views/components/inputCheckboxesSpec.scala
Aria described by changes
CYA bullet changes
Hint text change
Unit
Manual
> Amls 5817 - CYA and other accessibility changes

- app/views/components/answer_row.scala.html
Add id to answer row
N/A
Local
> Add id to answer row

- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- release_notes/AMLS-5748.txt
> Amls 5748 | Updated app dependencies

- conf/application.conf
Disable allowed hosts filter
N/A
Unit
> Disable allowed hosts filter

- conf/application.conf
Reverts hmrc/amls-art-market-participant-frontend#68
> Revert "Disable allowed hosts filter"

- project/build.properties
- project/plugins.sbt
> Revert sbt bump

- project/build.properties
- project/plugins.sbt
Reverts hmrc/amls-art-market-participant-frontend#67
> Revert "Revert sbt bump"

- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- release_notes/AMLS-5748.txt
Reverts hmrc/amls-art-market-participant-frontend#66
> Revert "Amls 5748 | Updated app dependencies"

- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- release_notes/AMLS-5748.txt
Reverts hmrc/amls-art-market-participant-frontend#71
> Revert "Revert "Amls 5748 | Updated app dependencies""

- app/views/components/input_checkboxes.scala.html
- release_notes/AMLS-5938.txt
As above.
- none
- manually
- wave
> Amls 5938 | Linked aria described by to hint for checkboxes

- app/forms/mappings/Constraints.scala
- release_notes/AMLS-5917.txt
- test/forms/DateTransactionOverThresholdFormProviderSpec.scala
- test/forms/mappings/ConstraintsSpec.scala
Remove TODOs from code
N/A
N/A
> AMLS-5917 | Remove TODOs from code

- test/forms/mappings/ConstraintsSpec.scala
> Remove commented out spec

- app/views/GovukWrapper.scala.html
Removal of beta banner header
Manually
> Amls beta header removal

- app/filters/AllowListFilter.scala
- test/filters/AllowListFilterSpec.scala
replacing usages of whitelist/ blacklist with allowList/ denyList
sbt clean compile test
> DLS-3126 updated language

- conf/application.conf
> DDCYLS-3901 Adding exit survey link to AMP frontend

- app/views/Layout.scala.html
- conf/application.conf
- test/resources/test.application.conf
> DDCYLS-4335 Adding CSP filter to AMP frontend

- app/config/FrontendAppConfig.scala
- conf/application.conf
> DDCYLS-4335 Exit survey update

- app/connectors/AMLSConnector.scala
- app/handlers/ErrorHandler.scala
- app/views/CheckYourAnswersView.scala.html
- app/views/DateTransactionOverThresholdView.scala.html
- app/views/ErrorTemplate.scala.html
- app/views/IdentifyLinkedTransactionsView.scala.html
- app/views/PercentageExpectedTurnoverView.scala.html
- app/views/SoldOverThresholdView.scala.html
- app/views/TypeOfParticipantDetailView.scala.html
- app/views/TypeOfParticipantView.scala.html
- app/views/UnauthorisedView.scala.html
- app/views/WhatYouNeedView.scala.html
- conf/application-json-logger.xml
- conf/application.conf
- conf/logback.xml
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/connectors/AMLSConnectorSpec.scala
- test/views/behaviours/ViewBehaviours.scala
Reverts hmrc/amls-art-market-participant-frontend#115
> Revert "Upgraded dependencies for all AMLS AMP libraries"

- README.md
> DDCYLS-6374 - ReadMe update

- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
> DDCYLS-6428: Dependency upgrade

- precheck.sh
> DDCYLS-6655 - Adding precheck sh file

- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
> DDCYLS-6912 - dependency upgrade
